# fly.toml app configuration file generated for node-auth on 2024-12-12T21:29:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-auth"
primary_region = "scl"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024

