# fly.toml app configuration file generated for node-auth on 2024-12-12T21:29:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'node-auth'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  size = 'shared-cpu-1x'

